require:
  - rubocop-rspec

inherit_from:
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop/security.yml
  - .rubocop/style.yml
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/*
    - vendor/bundle/**/*
  ExtraDetails: true
  TargetRubyVersion: 2.5
  UseCache: true

Style/Documentation:
  Exclude:
    - lib/bundler/source/s3.rb
    - spec/**/*
