inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/*
    - vendor/bundle/**/*
  ExtraDetails: true
  TargetRubyVersion: 2.5
  UseCache: true

Gemspec/OrderedDependencies:
  Enabled: true

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/NotToNot:
  Enabled: true
  EnforcedStyle: not_to

RSpec/ScatteredLet:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false

Layout/IndentHeredoc:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Lint/UselessAssignment:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining

Style/CharacterLiteral:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - lib/bundler/source/s3.rb
    - spec/**/*

Style/ExpandPathArguments:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  IgnoredMethods:
    # Language core
    - raise
    - require
    # Rspec
    - be
    - describe
    - expect
    - not_to
    - to
    # Rake
    - task
    # gem/bundler
    - add_dependency
    - add_development_dependency

Style/MutableConstant:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/UnneededPercentQ:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  CountComments: false
  ExcludedMethods:
    - context
    - describe
    - namespace
    - refine
    - task
