version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_REGION: ap-northeast-1
      - image: localstack/localstack:latest
        environment:
          SERVICES: s3
    steps:
      - run: gem install bundler
      - checkout
      - restore_cache:
          keys: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "bundler-source-s3.gemspec" }}
      - run: bin/setup
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "bundler-source-s3.gemspec" }}
          paths: vendor/bundle
      - run: bin/rake rubocop
      - run: bin/rake spec
      - run: bin/rake yard
